# -*- coding: utf-8 -*-
"""
Korean dog-breed input -> English breed slug mapper.

Usage:
    from dog_breed_mapper import match_dog_breed
    match_dog_breed('진돗개')          # 'jindo'
    match_dog_breed('토이푸들')        # 'toy-poodle'
    match_dog_breed('웰시코기')        # 'pembroke-welsh-corgi'
    match_dog_breed('골든 리트리버')   # 'golden-retriever'
"""
from __future__ import annotations

import re
import unicodedata
from typing import Optional
from difflib import get_close_matches, SequenceMatcher

BREEDS = {
    'abruzzenhund',
    'affenpinscher',
    'afghan-hound',
    'africanis',
    'aidi',
    'ainu-dog',
    'airedale',
    'airedale-terrier',
    'akbash-dog',
    'akita',
    'akita-american',
    'akita-inu-japanese',
    'akitas',
    'alano-espaol',
    'alano-español',
    'alapaha-blue-blood-bulldog',
    'alaskan-husky',
    'alaskan-klee-kai',
    'alaskan-malamute',
    'alopekis',
    'alpine-dachsbracke',
    'american-alsatian',
    'american-black-and-tan-coonhound',
    'american-blue-gascon-hound',
    'american-blue-lacy',
    'american-bulldog',
    'american-bullnese',
    'american-bully',
    'american-cocker-spaniel',
    'american-english-coonhound',
    'american-eskimo-dog',
    'american-foxhound',
    'american-hairless-terrier',
    'american-leopard-hound',
    'american-mastiff',
    'american-pit-bull-terrier',
    'american-staffordshire-terrier',
    'american-water-spaniel',
    'american-white-shepherd',
    'anatolian-shepherd-dog',
    'andalusian-podenco',
    'anglo-franaises-de-petite-venerie',
    'anglo-françaises-de-petite-venerie',
    'appenzell-mountain-dog',
    'appenzeller',
    'appenzeller-sennenhund',
    'argentine-dogo',
    'ariege-pointing-dog',
    'ariegeois',
    'armant',
    'armenian-gampr',
    'australian-bulldog',
    'australian-cattle-dog',
    'australian-cobberdog',
    'australian-kelpie',
    'australian-shepherd',
    'australian-stumpy-tail-cattle-dog',
    'australian-terrier',
    'austrian-black-and-tan-hound',
    'austrian-brandlbracke',
    'austrian-shorthaired-pinscher',
    'auvergne-pointing-dog',
    'azawakh',
    'balkan-hound',
    'balkan-scenthound',
    'balkanski-gonic',
    'banjara-hound',
    'barbado-da-terceira',
    'barbet',
    'basenji',
    'basset-artesien-normand',
    'basset-bleu-de-gascogne',
    'basset-fauve-de-bretagne',
    'basset-hound',
    'bavarian-mountain-scent-hound',
    'beagle',
    'beagle-harrier',
    'bearded-collie',
    'beauceron',
    'bedlington-terrier',
    'bedouin-shepherd-dog',
    'belgian-laekenois',
    'belgian-malinois',
    'belgian-sheepdog',
    'belgian-shepherd-groenendael',
    'belgian-shepherd-laekenois',
    'belgian-shepherd-malinois',
    'belgian-shepherd-tervuren',
    'belgian-tervuren',
    'bench-legged-feist',
    'bergamasco',
    'bergamasco-sheepdog',
    'berger-blanc-suisse',
    'berger-des-picard',
    'berger-des-pyrnes',
    'berger-des-pyrénées',
    'berger-picard',
    'bernese-hound',
    'bernese-mountain-dog',
    'bichon-frise',
    'bichon-havanais',
    'biewer',
    'biewer-terrier',
    'billy',
    'black-and-tan-coonhound',
    'black-forest-hound',
    'black-mouth-cur',
    'black-norwegian-elkhound',
    'black-russian-terrier',
    'bloodhound',
    'blue-lacy',
    'blue-picardy-spaniel',
    'bluetick',
    'bluetick-coonhound',
    'boerboel',
    'bohemian-shepherd',
    'bohemian-terrier',
    'bolognese',
    'border-collie',
    'border-terrier',
    'borzoi',
    'bosanski-ostrodlaki-gonic-barak',
    'bosnian-herzegovinian-sheepdog---tornjak',
    'boston-terrier',
    'bouvier',
    'bouvier-de-ardennes',
    'bouvier-des-flandres',
    'boxer',
    'boykin-spaniel',
    'bracco-italiano',
    'braque-du-bourbonnais',
    'braque-francais-gascogne',
    'braque-francais-pyrenean',
    'brazilian-terrier',
    'briard',
    'briquet-griffon-vendeen',
    'brittany',
    'brittany-spaniel',
    'broholmer',
    'brussels-griffon',
    'bukovina-sheepdog',
    'buldogue-campeiro',
    'bull-terrier',
    'bulldog',
    'bullmastiff',
    'bully-kutta',
    'cairn-terrier',
    'canaan-dog',
    'canadian-eskimo-dog',
    'canadian-inuit-dog',
    'canarian-warren-hound',
    'canary-dog',
    'cane-corso',
    'cane-corso-italiano',
    'cardigan-welsh-corgi',
    'carolina-dog',
    'carpathian-sheepdog',
    'catahoula-leopard-dog',
    'catalan-sheepdog',
    'caucasian-ovtcharka',
    'caucasian-shepherd-dog',
    'cavalier-king-charles-spaniel',
    'central-asian-ovtcharka',
    'central-asian-shepherd-dog',
    'cesky-fousek',
    'cesky-terrier',
    'chart-polski',
    'chesapeake-bay-retriever',
    'chien-dartois',
    'chien-de-l-atlas',
    'chihuahua',
    'chin',
    'chinese-chongqing-dog',
    'chinese-crested',
    'chinese-shar-pei',
    'chinook',
    'chippiparai',
    'chow',
    'chow-chow',
    'chuandong-hound',
    'chukotka-sledge-dog',
    'cimarron-uruguayo',
    'cirneco-delletna',
    'clumber',
    'clumber-spaniel',
    'co-da-serra-da-estrela',
    'co-da-serra-de-aires',
    'co-de-castro-laboreiro',
    'co-de-fila-de-so-miguel',
    'co-de-gado-transmontano',
    'collie',
    'collie-rough-and-smooth',
    'continental-bulldog',
    'continental-toy-spaniel',
    'corgi',
    'coton-de-tulear',
    'cretan-hound',
    'croatian-sheepdog',
    'curly-coated-retriever',
    'czechoslovakian-vlcak',
    'czechoslovakian-wolfdog',
    'czesky-terrier',
    'cão-da-serra-da-estrela',
    'cão-da-serra-de-aires',
    'cão-de-castro-laboreiro',
    'cão-de-fila-de-são-miguel',
    'cão-de-gado-transmontano',
    'dachshund',
    'dalmatian',
    'dandie-dinmont-terrier',
    'danish-broholmer',
    'danish-swedish-farmdog',
    'deutsch-drahthaar',
    'deutsche-bracke-see-photo-needed',
    'deutscher-wachtelhund',
    'dingo',
    'doberman',
    'doberman-pinscher',
    'dogo-argentino',
    'dogue-de-bordeaux',
    'dosa-inu',
    'drentsche-patrijshond',
    'drentse-patrijshond',
    'drever',
    'dunker',
    'dutch-shepherd',
    'dutch-shepherd-dog',
    'dutch-smoushond',
    'east-european-shepherd',
    'east-siberian-laika',
    'elkhound-see-norwegian-elkhound',
    'english-bulldog',
    'english-cocker-spaniel',
    'english-coonhound',
    'english-foxhound',
    'english-pointer',
    'english-setter',
    'english-shepherd',
    'english-springer-spaniel',
    'english-toy-spaniel',
    'entlebucher',
    'entlebucher-mountain-dog',
    'entlebucher-sennenhund',
    'eskimo',
    'estonian-hound',
    'estrela-mountain-dog',
    'eurasier',
    'field-spaniel',
    'fila-brasileiro',
    'finnish-hound',
    'finnish-lapphund',
    'finnish-spitz',
    'flat-coated-retriever',
    'french-brittany-spaniel',
    'french-bulldog',
    'french-mastiff',
    'french-spaniel',
    'french-tricolor-hound',
    'french-white-and-black-hound',
    'french-white-and-orange-hound',
    'galgo-espaol',
    'galgo-español',
    'gammel-dansk-hoensehund',
    'gascons-saintongeois',
    'georgian-mountain-dog',
    'german-hunt-terrier',
    'german-longhaired-pointer',
    'german-pinscher',
    'german-rough-haired-pointing-dog',
    'german-shepherd-dog',
    'german-shorthaired-pointer',
    'german-spitz-giant',
    'german-spitz-medium',
    'german-spitz-small',
    'german-wirehaired-pointer',
    'giant-schnauzer',
    'glen-of-imaal-terrier',
    'golden-retriever',
    'gordon-setter',
    'grand-anglo-franais-blanc-et-noir',
    'grand-anglo-franais-blanc-et-orange',
    'grand-anglo-franais-tricolore',
    'grand-anglo-français-blanc-et-noir',
    'grand-anglo-français-blanc-et-orange',
    'grand-anglo-français-tricolore',
    'grand-basset-griffon-vendeen',
    'grand-basset-griffon-venden',
    'grand-bleu-de-gascogne',
    'grand-gascon-saintongeois',
    'grand-griffon-vendeen',
    'great-dane',
    'great-pyrenees',
    'greater-swiss-mountain-dog',
    'greek-hound',
    'greek-sheepdog',
    'greenland-dog',
    'greyhound',
    'griffon-bleu-de-gascogne',
    'griffon-fauve-de-bretagne',
    'griffon-nivernais',
    'groenendael',
    'grosser-mnsterlander-vorstehhund',
    'grosser-münsterlander-vorstehhund',
    'gull-dong',
    'gull-terrier',
    'halden-hound',
    'hamilton-hound',
    'hamiltonstovare',
    'hanoverian-hound',
    'hanoverian-scenthound',
    'harrier',
    'havanese',
    'hellenikos-ichnilatis',
    'himalayan-sheepdog',
    'hokkaido',
    'hokkaido-dog',
    'hortaya-borzaya',
    'hovawart',
    'hungarian-kuvasz',
    'hungarian-puli',
    'hungarian-wire-haired-pointing-dog',
    'hygenhund',
    'ibizan-hound',
    'icelandic-sheepdog',
    'indian-spitz',
    'irish-glen-imaal-terrier',
    'irish-red-and-white-setter',
    'irish-setter',
    'irish-terrier',
    'irish-water-spaniel',
    'irish-wolfhound',
    'istrian-coarse-haired-hound-photo-needed',
    'istrian-shorthaired-hound',
    'italian-greyhound',
    'italian-spinoni',
    'jack-russell-terrier',
    'jagdterrier',
    'jamthund',
    'japanese-akitainu',
    'japanese-chin',
    'japanese-spaniel-chin',
    'japanese-spitz',
    'japanese-terrier',
    'jindo',
    'kai-dog',
    'kai-ken',
    'kangal-dog',
    'kanni',
    'karakachan',
    'karelian-bear-dog',
    'karelian-bear-laika',
    'karst-shepherd',
    'keeshond',
    'kelb-tal-fenek',
    'kelpie',
    'kerry-beagle',
    'kerry-blue-terrier',
    'king-charles-spaniel',
    'king-shepherd',
    'kishu-ken',
    'kokoni',
    'kombai',
    'komondor',
    'kooikerhondje',
    'koolie',
    'krasky-ovcar',
    'kromfohrlander',
    'kunming-dog',
    'kuvasz',
    'kyi-leo',
    'labrador',
    'labrador-retriever',
    'lagotto-romagnolo',
    'lakeland-terrier',
    'lancashire-heeler',
    'landseer',
    'lapinporokoira',
    'lapponian-herder',
    'large-mnsterlnder',
    'large-münsterländer',
    'latvian-hound',
    'leonberg',
    'leonberger',
    'lhasa',
    'lhasa-apso',
    'lithuanian-hound',
    'llewellin-setter',
    'louisiana-catahoula-leopard-dog',
    'lucas-terrier',
    'lundehund',
    'lwchen',
    'lwchen-little-lion-dog',
    'löwchen-little-lion-dog',
    'magyar-agar',
    'mahratta-hound',
    'majorca-shepherd-dog',
    'malamute',
    'malinois',
    'maltese',
    'manchester-terrier',
    'manchester-terrier-standard',
    'manchester-terrier-toy',
    'maremma-sheepdog',
    'markiesje',
    'mastiff',
    'mcnab',
    'mexican-hairless',
    'mi-ki',
    'middle-asian-ovtcharka',
    'miniature-american-eskimo',
    'miniature-american-shepherd',
    'miniature-bull-terrier',
    'miniature-fox-terrier',
    'miniature-pinscher',
    'miniature-poodle',
    'miniature-schnauzer',
    'montenegrin-mountain-hound',
    'moscow-watchdog',
    'mountain-cur',
    'mountain-feist',
    'mucuchies',
    'mudhol-hound',
    'mudi',
    'neapolitan-mastiff',
    'nederlandse-kooikerhondje',
    'nenets-herding-laika',
    'new-guinea-singing-dog',
    'new-zealand-huntaway',
    'newfoundland',
    'norfolk-terrier',
    'norrbottenspets',
    'north-american-indian-dog',
    'north-american-miniature-australian-shepherd',
    'northern-inuit-dog',
    'norwegian-buhund',
    'norwegian-elkhound',
    'norwegian-hound',
    'norwegian-lundehund',
    'norwich-terrier',
    'nova-scotia-duck-tolling-retriever',
    'old-danish-chicken-dog',
    'old-english-mastiff',
    'old-english-sheepdog',
    'old-english-sheepdog-bobtail',
    'olde-english-bulldogge',
    'otterhound',
    'owczarek-podhalanski',
    'pachon-navarro',
    'papillon',
    'parson-russell-terrier',
    'patterdale-terrier',
    'patti',
    'pekingese',
    'pembroke',
    'pembroke-welsh-corgi',
    'perdiguero-de-burgos',
    'perro-cimarron',
    'perro-de-pastor-mallorquin',
    'perro-de-presa-canario',
    'perro-de-presa-mallorquin',
    'perro-dogo-mallorquin',
    'perro-ratonero-andaluz',
    'peruvian-inca-orchid',
    'peruvian-inca-orchid-pio',
    'petit-basset-griffon-vendeen',
    'petit-basset-griffon-venden',
    'petit-bleu-de-gascogne',
    'petit-brabancon',
    'petit-gascon-saintongeois',
    'pharaoh-hound',
    'phu-quoc-ridgeback-dog',
    'picardy-spaniel',
    'plott-hound',
    'plummer-terrier',
    'podenco-ibicenco',
    'pointer',
    'poitevin',
    'polish-hound',
    'polish-lowland-sheepdog',
    'polish-tatra-sheepdog',
    'pomeranian',
    'poodle',
    'poodle-miniature',
    'poodle-standard',
    'poodle-toy',
    'porcelaine',
    'portuguese-podengo',
    'portuguese-podengo-pequeno',
    'portuguese-pointer',
    'portuguese-sheepdog',
    'portuguese-water-dog',
    'posavac-hound',
    'prazsky-krysavik',
    'presa-canario',
    'pudelpointer',
    'pug',
    'puli',
    'puli-pulik',
    'pumi',
    'pyrenean-mastiff',
    'pyrenean-mountain-dog',
    'pyrenean-shepherd',
    'rafeiro-do-alentejo',
    'rajapalayam',
    'rampur-hound',
    'rastreador-brasileiro',
    'rat-terrier',
    'redbone',
    'redbone-coonhound',
    'rhodesian-ridgeback',
    'romanian-mioritic-shepherd-dog',
    'rottweiler',
    'rough-collie',
    'russell-terrier',
    'russian-hound',
    'russian-pied-hound',
    'russian-spaniel',
    'russian-toy',
    'russian-tsvetnaya-bolonka',
    'russo-european-laika',
    'saarlooswolfhond',
    'sabueso-espaol',
    'sabueso-español',
    'saint-bernard',
    'saluki',
    'samoyed',
    'sapsari',
    'sarplaninac',
    'schafpudel',
    'schapendoes',
    'schiller-hound',
    'schipperke',
    'schnauzer',
    'scotch-collie',
    'scottish-deerhound',
    'scottish-terrier',
    'scottish-terrier-scottie',
    'sealyham-terrier',
    'segugio-italiano',
    'serbian-hound',
    'shetland-sheepdog',
    'shiba-inu',
    'shih-tzu',
    'shikoku',
    'shiloh-shepherd',
    'siberian-husky',
    'silken-windhound',
    'silky-terrier',
    'skye-terrier',
    'sloughi',
    'slovensky-cuvac',
    'slovensky-hrubosrsty-stavac',
    'slovensky-kopov',
    'smalandsstovare',
    'small-munsterlander',
    'small-swiss-hound',
    'smooth-collie',
    'smooth-fox-terrier',
    'soft-coated-wheaten-terrier',
    'south-russian-ovtcharka',
    'spaniel-de-pont-audemer',
    'spanish-hound',
    'spanish-mastiff',
    'spanish-water-dog',
    'spinone-italiano',
    'springer-spaniel',
    'srpski-gonic',
    'srpski-trobojni-gonic',
    'st-germain-pointing-dog',
    'stabyhoun',
    'staffordshire-bull-terrier',
    'standard-american-eskimo',
    'standard-poodle',
    'standard-schnauzer',
    'stephens-stock-mountain-cur',
    'stichelhaar',
    'styrian-roughhaired-mountain-hound',
    'sussex-spaniel',
    'swedish-lapphund',
    'swedish-vallhund',
    'swiss-hound',
    'taigan',
    'taiwan-dog',
    'tamaskan-dog',
    'tangkhul-hui',
    'tasy',
    'teddy-roosevelt-terrier',
    'telomian',
    'tenterfield-terrier',
    'thai-bangkaew-dog',
    'thai-ridgeback',
    'tibetan-kyiapso',
    'tibetan-mastiff',
    'tibetan-spaniel',
    'tibetan-terrier',
    'tornjak',
    'tosa',
    'toy-fox-terrier',
    'toy-manchester-terrier',
    'toy-poodle',
    'transylvanian-hound',
    'treeing-tennessee-brindle',
    'treeing-walker-coonhound',
    'tuareg-sloughi',
    'tyroler-bracke',
    'ukrainian-carpathian-hound',
    'utonagan',
    'victorian-bulldog',
    'villano-de-las-encartaciones',
    'vizsla',
    'volpino-italiano',
    'vucciriscu',
    'weimaraner',
    'welsh-sheepdog',
    'welsh-springer-spaniel',
    'welsh-terrier',
    'west-highland-white-terrier',
    'west-siberian-laika',
    'westphalian-dachsbracke',
    'wetterhoun',
    'whippet',
    'white-swiss-shepherd',
    'wire-fox-terrier',
    'wirehaired-pointing-griffon',
    'wirehaired-vizsla',
    'xoloitzcuintli',
    'yakutian-laika',
    'yorkshire-terrier',
    'yugoslavian-hound',
}

# 많이 쓰는 한국어 품종명/별칭 매핑입니다. 값은 위 BREEDS의 영어 slug여야 합니다.
# 새 품종/별칭이 필요하면 이 dict에 한 줄만 추가하면 됩니다.
KO_TO_EN = {
    # 한국/일본/아시아권
    '진도': 'jindo', '진돗개': 'jindo', '진도개': 'jindo', '코리안진도': 'jindo',
    '삽살개': 'sapsari', '삽사리': 'sapsari',
    '시바': 'shiba-inu', '시바견': 'shiba-inu', '시바이누': 'shiba-inu',
    '아키타': 'akita', '아키타견': 'akita', '아키타이누': 'akita-inu-japanese', '일본아키타': 'akita-inu-japanese', '아메리칸아키타': 'akita-american',
    '홋카이도견': 'hokkaido-dog', '홋카이도': 'hokkaido', '카이켄': 'kai-ken', '카이견': 'kai-ken', '기슈견': 'kishu-ken', '시코쿠견': 'shikoku',
    '재패니즈친': 'japanese-chin', '일본친': 'japanese-chin', '재패니즈스피츠': 'japanese-spitz', '일본스피츠': 'japanese-spitz', '재패니즈테리어': 'japanese-terrier',
    '차우차우': 'chow-chow', '차우': 'chow-chow', '샤페이': 'chinese-shar-pei', '차이니즈샤페이': 'chinese-shar-pei',
    '차이니즈크레스티드': 'chinese-crested', '중국크레스티드': 'chinese-crested', '충칭견': 'chinese-chongqing-dog',
    '타이완독': 'taiwan-dog', '대만견': 'taiwan-dog', '타이리지백': 'thai-ridgeback', '타이방깨우': 'thai-bangkaew-dog',
    '풍산개': 'jindo',  # 목록에 pung-san/pungsan이 없으므로 가장 가까운 한국 토종견으로 처리하지 않으려면 이 줄 제거
    '토사': 'tosa', '도사견': 'tosa', '도사이누': 'tosa', '티베탄마스티프': 'tibetan-mastiff', '티베탄스패니얼': 'tibetan-spaniel', '티베탄테리어': 'tibetan-terrier',
    '라사압소': 'lhasa-apso', '페키니즈': 'pekingese', '파라오하운드': 'pharaoh-hound',

    # 리트리버/스패니얼/세터/포인터
    '골든리트리버': 'golden-retriever', '골든 리트리버': 'golden-retriever',
    '래브라도': 'labrador-retriever', '라브라도': 'labrador-retriever', '래브라도리트리버': 'labrador-retriever', '라브라도리트리버': 'labrador-retriever', '랩': 'labrador-retriever',
    '체서피크베이리트리버': 'chesapeake-bay-retriever', '플랫코티드리트리버': 'flat-coated-retriever', '컬리코티드리트리버': 'curly-coated-retriever', '노바스코샤덕톨링리트리버': 'nova-scotia-duck-tolling-retriever',
    '코커스패니얼': 'american-cocker-spaniel', '아메리칸코커스패니얼': 'american-cocker-spaniel', '잉글리시코커스패니얼': 'english-cocker-spaniel',
    '카발리에킹찰스스패니얼': 'cavalier-king-charles-spaniel', '킹찰스스패니얼': 'king-charles-spaniel', '잉글리시토이스패니얼': 'english-toy-spaniel',
    '브리타니': 'brittany', '브리타니스패니얼': 'brittany-spaniel', '잉글리시스프링거스패니얼': 'english-springer-spaniel', '스프링거스패니얼': 'springer-spaniel',
    '웰시스프링거스패니얼': 'welsh-springer-spaniel', '필드스패니얼': 'field-spaniel', '클럼버스패니얼': 'clumber-spaniel', '서식스스패니얼': 'sussex-spaniel', '아이리시워터스패니얼': 'irish-water-spaniel',
    '잉글리시포인터': 'english-pointer', '포인터': 'pointer', '저먼쇼트헤어드포인터': 'german-shorthaired-pointer', '저먼와이어헤어드포인터': 'german-wirehaired-pointer',
    '비즐라': 'vizsla', '와이어헤어드비즐라': 'wirehaired-vizsla', '고든세터': 'gordon-setter', '아이리시세터': 'irish-setter', '잉글리시세터': 'english-setter',

    # 푸들/비숑/말티즈/소형 반려견
    '푸들': 'poodle', '스탠다드푸들': 'standard-poodle', '미니어처푸들': 'miniature-poodle', '미니푸들': 'miniature-poodle', '토이푸들': 'toy-poodle',
    '비숑': 'bichon-frise', '비숑프리제': 'bichon-frise', '비숑프리세': 'bichon-frise',
    '말티즈': 'maltese', '몰티즈': 'maltese', '하바니즈': 'havanese', '꼬똥드툴레아': 'coton-de-tulear', '코통드튈레아': 'coton-de-tulear',
    '볼로네즈': 'bolognese', '로첸': 'lwchen', '뢰첸': 'lwchen', '파피용': 'papillon', '퍼그': 'pug',
    '치와와': 'chihuahua', '포메라니안': 'pomeranian', '요크셔테리어': 'yorkshire-terrier', '요키': 'yorkshire-terrier',
    '시츄': 'shih-tzu', '시추': 'shih-tzu', '미니어처핀셔': 'miniature-pinscher', '미니핀': 'miniature-pinscher', '이탈리안그레이하운드': 'italian-greyhound',
    '러시안토이': 'russian-toy', '아펜핀셔': 'affenpinscher', '브뤼셀그리폰': 'brussels-griffon', '쁘띠브라반송': 'petit-brabancon',

    # 코기/콜리/목양견
    '웰시코기': 'pembroke-welsh-corgi', '펨브록웰시코기': 'pembroke-welsh-corgi', '카디건웰시코기': 'cardigan-welsh-corgi', '코기': 'corgi',
    '보더콜리': 'border-collie', '러프콜리': 'rough-collie', '스무스콜리': 'smooth-collie', '콜리': 'collie', '비어디드콜리': 'bearded-collie',
    '셰틀랜드쉽독': 'shetland-sheepdog', '셸티': 'shetland-sheepdog', '올드잉글리시쉽독': 'old-english-sheepdog', '보브테일': 'old-english-sheepdog-bobtail',
    '저먼셰퍼드': 'german-shepherd-dog', '독일셰퍼드': 'german-shepherd-dog', '화이트셰퍼드': 'american-white-shepherd', '스위스화이트셰퍼드': 'white-swiss-shepherd',
    '벨지안말리노이즈': 'belgian-shepherd-malinois', '말리노이즈': 'belgian-shepherd-malinois', '그로넨달': 'belgian-shepherd-groenendael', '테뷰런': 'belgian-shepherd-tervuren', '라케노이즈': 'belgian-shepherd-laekenois',
    '오스트레일리안셰퍼드': 'australian-shepherd', '오스트레일리언셰퍼드': 'australian-shepherd', '오지': 'australian-shepherd', '미니어처아메리칸셰퍼드': 'miniature-american-shepherd',
    '오스트레일리안캐틀독': 'australian-cattle-dog', '켈피': 'australian-kelpie', '오스트레일리안켈피': 'australian-kelpie', '스키퍼키': 'schipperke', '코몬도르': 'komondor', '쿠바스': 'kuvasz', '풀리': 'puli', '푸미': 'pumi', '무디': 'mudi',
    '보스롱': 'beauceron', '브리아드': 'briard', '피카르디셰퍼드': 'berger-picard', '버거피카드': 'berger-picard',
    '버니즈마운틴독': 'bernese-mountain-dog', '버니즈마운틴': 'bernese-mountain-dog', '그레이터스위스마운틴독': 'greater-swiss-mountain-dog', '엔틀부허마운틴독': 'entlebucher-mountain-dog', '아펜젤러': 'appenzeller-sennenhund',

    # 테리어
    '잭러셀테리어': 'jack-russell-terrier', '잭러셀': 'jack-russell-terrier', '러셀테리어': 'russell-terrier', '파슨러셀테리어': 'parson-russell-terrier',
    '불테리어': 'bull-terrier', '미니어처불테리어': 'miniature-bull-terrier', '스태퍼드셔불테리어': 'staffordshire-bull-terrier', '아메리칸스태퍼드셔테리어': 'american-staffordshire-terrier',
    '핏불': 'american-pit-bull-terrier', '아메리칸핏불테리어': 'american-pit-bull-terrier', '보스턴테리어': 'boston-terrier', '폭스테리어': 'wire-fox-terrier', '와이어폭스테리어': 'wire-fox-terrier', '스무스폭스테리어': 'smooth-fox-terrier',
    '웨스트하이랜드화이트테리어': 'west-highland-white-terrier', '웨스티': 'west-highland-white-terrier', '스코티시테리어': 'scottish-terrier', '스코티': 'scottish-terrier-scottie',
    '케언테리어': 'cairn-terrier', '노퍽테리어': 'norfolk-terrier', '노리치테리어': 'norwich-terrier', '요크셔테리어': 'yorkshire-terrier',
    '에어데일테리어': 'airedale-terrier', '베들링턴테리어': 'bedlington-terrier', '보더테리어': 'border-terrier', '케리블루테리어': 'kerry-blue-terrier', '레이크랜드테리어': 'lakeland-terrier',
    '맨체스터테리어': 'manchester-terrier', '토이맨체스터테리어': 'toy-manchester-terrier', '실키테리어': 'silky-terrier', '스카이테리어': 'skye-terrier', '소프트코티드휘튼테리어': 'soft-coated-wheaten-terrier',

    # 불독/마스티프/몰로서
    '불독': 'bulldog', '잉글리시불독': 'english-bulldog', '프렌치불독': 'french-bulldog', '프불': 'french-bulldog', '아메리칸불독': 'american-bulldog',
    '복서': 'boxer', '불마스티프': 'bullmastiff', '마스티프': 'mastiff', '잉글리시마스티프': 'old-english-mastiff', '나폴리탄마스티프': 'neapolitan-mastiff', '티베탄마스티프': 'tibetan-mastiff',
    '도고아르헨티노': 'dogo-argentino', '도그드보르도': 'dogue-de-bordeaux', '프렌치마스티프': 'french-mastiff', '카네코르소': 'cane-corso', '케인코르소': 'cane-corso',
    '로트와일러': 'rottweiler', '도베르만': 'doberman-pinscher', '도베르만핀셔': 'doberman-pinscher', '그레이트데인': 'great-dane', '세인트버나드': 'saint-bernard', '뉴펀들랜드': 'newfoundland',
    '레온베르거': 'leonberger', '보어보엘': 'boerboel', '프레사카나리오': 'presa-canario', '카나리독': 'canary-dog', '코카시안셰퍼드': 'caucasian-shepherd-dog', '중앙아시아셰퍼드': 'central-asian-shepherd-dog',

    # 하운드/사냥견
    '비글': 'beagle', '바셋하운드': 'basset-hound', '블러드하운드': 'bloodhound', '그레이하운드': 'greyhound', '휘핏': 'whippet', '보르조이': 'borzoi', '살루키': 'saluki', '아자와크': 'azawakh', '슬루기': 'sloughi',
    '아프간하운드': 'afghan-hound', '아이리시울프하운드': 'irish-wolfhound', '스코티시디어하운드': 'scottish-deerhound', '닥스훈트': 'dachshund', '닥스': 'dachshund',
    '로디지안리지백': 'rhodesian-ridgeback', '바센지': 'basenji', '플롯하운드': 'plott-hound', '레드본쿤하운드': 'redbone-coonhound', '블루틱쿤하운드': 'bluetick-coonhound', '블랙앤탄쿤하운드': 'black-and-tan-coonhound',
    '아메리칸폭스하운드': 'american-foxhound', '잉글리시폭스하운드': 'english-foxhound', '해리어': 'harrier', '오터하운드': 'otterhound', '파라오하운드': 'pharaoh-hound', '이비잔하운드': 'ibizan-hound',

    # 스피츠/북방견
    '허스키': 'siberian-husky', '시베리안허스키': 'siberian-husky', '알래스칸말라뮤트': 'alaskan-malamute', '말라뮤트': 'malamute', '알래스칸허스키': 'alaskan-husky', '알래스칸클리카이': 'alaskan-klee-kai',
    '사모예드': 'samoyed', '스피츠': 'finnish-spitz', '피니시스피츠': 'finnish-spitz', '인디언스피츠': 'indian-spitz', '볼피노이탈리아노': 'volpino-italiano',
    '아메리칸에스키모독': 'american-eskimo-dog', '에스키모독': 'american-eskimo-dog', '키스혼드': 'keeshond', '노르웨이안엘크하운드': 'norwegian-elkhound', '엘크하운드': 'norwegian-elkhound',
    '핀란드라프훈드': 'finnish-lapphund', '스웨디시라프훈드': 'swedish-lapphund', '노르웨이안부훈드': 'norwegian-buhund', '노르웨이안룬데훈드': 'norwegian-lundehund',
    '유라시어': 'eurasier', '그린란드독': 'greenland-dog', '캐나디안에스키모독': 'canadian-eskimo-dog', '카렐리안베어독': 'karelian-bear-dog',
    '자이언트슈나우저': 'giant-schnauzer', '스탠다드슈나우저': 'standard-schnauzer', '미니어처슈나우저': 'miniature-schnauzer', '슈나우저': 'schnauzer',

    # 기타 인기/대표 품종
    '달마시안': 'dalmatian', '와이마라너': 'weimaraner', '브라코이탈리아노': 'bracco-italiano', '스피노네이탈리아노': 'spinone-italiano', '라고토로마뇰로': 'lagotto-romagnolo',
    '포르투기즈워터독': 'portuguese-water-dog', '스패니시워터독': 'spanish-water-dog', '아이리시테리어': 'irish-terrier', '아이리시글렌오브이말테리어': 'irish-glen-imaal-terrier',
    '멕시칸헤어리스': 'mexican-hairless', '솔로이츠퀸틀리': 'xoloitzcuintli', '페루비안잉카오키드': 'peruvian-inca-orchid',
    '카타훌라레오파드독': 'catahoula-leopard-dog', '캐롤라이나독': 'carolina-dog', '치누크': 'chinook', '블랙마우스커': 'black-mouth-cur', '마운틴커': 'mountain-cur',
}


def _normalize(text: str) -> str:
    """한글/영문 품종 입력을 비교 가능한 형태로 정규화합니다."""
    text = unicodedata.normalize('NFKC', text or '').strip().lower()
    text = re.sub(r'[\s_]+', '-', text)
    text = re.sub(r'[^0-9a-z가-힣ñéèêáàäöüçãõíóú-]+', '', text)
    # 한국어 별칭은 공백/하이픈 없이도 매칭되게 처리
    return text.strip('-')


def _ko_key(text: str) -> str:
    return re.sub(r'[-\s]+', '', _normalize(text))


# 공백/하이픈 차이를 흡수한 alias index
_KO_INDEX = {_ko_key(k): v for k, v in KO_TO_EN.items()}
_EN_INDEX = {_normalize(b): b for b in BREEDS}
_EN_COMPACT_INDEX = {re.sub(r'-+', '', b): b for b in BREEDS}

# 한국어 오타/표기 흔들림 보정용
_KO_CHOICES = list(_KO_INDEX.keys())

# 자주 예상되는 오타는 명시적으로 먼저 처리
_KO_TYPO_INDEX = {
    '와이마리너': 'weimaraner',
    '와이머라너': 'weimaraner',
    '와이마라나': 'weimaraner',
}

def match_dog_breed(name: str, *, fuzzy: bool = True) -> Optional[str]:
    """
    한국어/영어 품종명을 영어 slug로 변환합니다.

    Args:
        name: 예) '진돗개', '토이푸들', 'golden retriever', 'welsh-corgi'
        fuzzy: True면 정확 매칭 실패 시 유사 영문 slug를 보조 검색합니다.

    Returns:
        첨부 품종 목록에 존재하는 영어 slug. 못 찾으면 None.
    """
    if not name or not name.strip():
        return None

    norm = _normalize(name)
    compact = _ko_key(name)

    # 1) 한국어 별칭 정확 매칭
    if compact in _KO_INDEX:
        return _KO_INDEX[compact]

    # 1-1) 자주 예상되는 한국어 오타 직접 보정
    if compact in _KO_TYPO_INDEX:
        return _KO_TYPO_INDEX[compact]

    # 1-2) 한국어 유사도 보정: '와이마리너' -> '와이마라너'
    if fuzzy and len(compact) >= 3:
        ko_matches = get_close_matches(compact, _KO_CHOICES, n=1, cutoff=0.78)
        if ko_matches:
            candidate = ko_matches[0]

            # 너무 짧은 단어가 엉뚱하게 붙는 것 방지
            similarity = SequenceMatcher(None, compact, candidate).ratio()
            length_gap = abs(len(compact) - len(candidate))

            if similarity >= 0.78 and length_gap <= 2:
                return _KO_INDEX[candidate]

    # 2) 영어 slug/영어 품종명 직접 매칭: 'golden retriever' -> 'golden-retriever'
    if norm in _EN_INDEX:
        return _EN_INDEX[norm]
    if norm.replace('-', '') in _EN_COMPACT_INDEX:
        return _EN_COMPACT_INDEX[norm.replace('-', '')]

    # 3) 한국어 부분 매칭: '우리집 말티즈 믹스' -> 'maltese'
    for ko, en in sorted(_KO_INDEX.items(), key=lambda kv: len(kv[0]), reverse=True):
        if ko and ko in compact:
            return en

    # 4) 영문 유사도 보정: 'golden retreiver' -> 'golden-retriever'
    if fuzzy:
        choices = list(BREEDS)
        matches = get_close_matches(norm, choices, n=1, cutoff=0.84)
        if matches:
            return matches[0]

    return None


def match_dog_breed_or_raise(name: str) -> str:
    breed = match_dog_breed(name)
    if breed is None:
        raise ValueError(f'Unknown dog breed: {name!r}')
    return breed
